- elements/10_electric/20_manufacturers_articles/johnson_controls/jc_a25cn-9001.elmt
- elements/10_electric/20_manufacturers_articles/johnson_controls/jc_ht-9001_udx.elmt
- elements/10_electric/20_manufacturers_articles/johnson_controls/jc_p233_a4-phc.elmt
- elements/10_electric/20_manufacturers_articles/johnson_controls/jc_p48aaa-9120.elmt
- elements/10_electric/20_manufacturers_articles/johnson_controls/jc_ps-9101.elmt
- elements/10_electric/20_manufacturers_articles/johnson_controls/jc_pt-5215.elmt
- elements/10_electric/20_manufacturers_articles/johnson_controls/jc_va-7312.elmt
- elements/10_electric/20_manufacturers_articles/phoenix_contact/phoenix_contact_2744461.elmt
- elements/10_electric/20_manufacturers_articles/phoenix_contact/phoenix_contact_2761266.elmt
- elements/10_electric/20_manufacturers_articles/phoenix_contact/phoenix_contact_2810913.elmt
- elements/10_electric/20_manufacturers_articles/phoenix_contact/phoenix_contact_2813512.elmt
- elements/10_electric/20_manufacturers_articles/phoenix_contact/phoenix_contact_2864082.elmt
- elements/10_electric/20_manufacturers_articles/phoenix_contact/phoenix_contact_psm_eg_rs232_2761266.elmt
- elements/10_electric/20_manufacturers_articles/phoenix_contact/phoenix_contact_psm_me_r232_rs485_p.elmt
- elements/10_electric/20_manufacturers_articles/sofrel/01_PLC_controllers/s500/sof_s510-8di-4ai-2do-dl_hf.elmt
- elements/10_electric/20_manufacturers_articles/sofrel/01_PLC_controllers/s500/sof_s510-8di-4ai-2do.elmt
- elements/10_electric/20_manufacturers_articles/sofrel/01_PLC_controllers/s500/sof_s550-8di-4ai-2do-rtc-dl_hf.elmt
- elements/10_electric/20_manufacturers_articles/sofrel/01_PLC_controllers/s500/sof_s550-8di-4ai-2do-rtc.elmt
- elements/10_electric/20_manufacturers_articles/sofrel/01_PLC_controllers/s500/sof_s550_ce_8di.elmt
- elements/10_electric/20_manufacturers_articles/sofrel/01_PLC_controllers/s500/sof_s550_cs_4ai.elmt
- elements/10_electric/20_manufacturers_articles/sofrel/01_PLC_controllers/s500/sof_s550_cs_4do.elmt
New symbols:
phoenix_contact
johnson_controls
sofrel
> Added new symbols

- cmake/qet_compilation_vars.cmake
When creating new files.
Add the new files to: "cmake/qet_compilation_vars.cmake".
So that Cmake stays up to date.
thank you.
> Fix Cmake build

- sources/qetapp.cpp
... to fix the problem, Laurent noted in QET-Forum.
> fix: set default "company-element-dir"

- sources/autoNum/ui/selectautonumw.cpp
- sources/diagram.cpp
- sources/diagramcontext.h
- sources/editor/graphicspart/partterminal.cpp
- sources/elementdialog.cpp
- sources/elementsmover.cpp
- sources/exportdialog.cpp
- sources/machine_info.cpp
- sources/main.cpp
- sources/properties/elementdata.cpp
- sources/properties/terminaldata.cpp
- sources/qetapp.cpp
- sources/qetapp.h
- sources/qetdiagrameditor.cpp
- sources/qetgraphicsitem/qetshapeitem.cpp
- sources/qetproject.cpp
- sources/qetproject.h
- sources/qetversion.cpp
- sources/qetversion.h
- sources/qetxml.cpp
- sources/qetxml.h
I don't like warnings...
in that context: I found some indentations with blanks ==> replaced by &lt;tab&gt;
And:
The title in MessageBox "Project-Setting -> AutoNumbering -> Elements -> Help" was confusing. See https://qelectrotech.org/forum/viewtopic.php?id=2725
There was no separate Help-Text available ==> added separate MessageBox
> some minor changes

- sources/qet_elementscaler/qet_elementscaler.cpp
- sources/ui/aboutqetdialog.cpp
I was irritated that I first had to select the most recent LOG file and that the most recent entry in the file was not displayed...
> About QET: improvements in usability

- sources/ElementsCollection/elementcollectionhandler.cpp
- sources/ElementsCollection/elementscollectionwidget.cpp
- sources/ElementsCollection/elementslocation.cpp
- sources/qetinformation.h
- sources/ui/dynamicelementtextmodel.cpp
No code-change!
No need to accept PR soon...
> fix typos and whitespace

- sources/ui/configpage/configpages.h
- sources/ui/diagrampropertiesdialog.cpp
- sources/ui/titleblockpropertieswidget.cpp
No code-change ... only formatting
> Fix typo and some whitespace

- sources/diagramview.cpp
As described in this Forum-Thread:
[https://qelectrotech.org/forum/viewtopic.php?id=2864](url)
> Fix: Only scroll diagram-view, when moved text leaves visible area

- lang/qet_pt_BR.ts
> PT-BR language update

- sources/qet_elementscaler/qet_elementscaler.cpp
- sources/qet_elementscaler/qet_elementscaler.h
the two files were created in 2024, therefore no time-period has been entered so far..
> fix copyright-year

- sources/dxf/dxftoelmt.cpp
- sources/machine_info.cpp
- sources/main.cpp
- sources/qet_elementscaler/qet_elementscaler.cpp
- sources/qetapp.cpp
- sources/qetapp.h
- sources/ui/aboutqetdialog.cpp
the PR-conflicts are resolved now!
> set config- and data-dir to system-specific paths

- sources/machine_info.cpp
It may be helpful for users to find the right location for moving their configuration and/or data to the new path(s)
> machine_info.cpp: add explaining text for directory-list

- sources/diagramcommands.cpp
- sources/diagramcontent.cpp
- sources/qetgraphicsitem/element.cpp
- sources/qetgraphicsitem/terminal.cpp
NO code-change ... only formatting
> formatting / whitespace - unify declarations

- build-aux/windows/Lancer QET.bat
- cmake/start_options.cmake
- misc/Lancer QET.bat
- misc/launch_qet.sh
- qelectrotech.pro
- sources/qetapp.cpp
- sources/qetapp.h
- sources/qetarguments.cpp
- sources/qetarguments.h
including adjustments for "Lancer_QET.bat" 
Some French texts may be have to be adjusted, because my French is very poor...
> add commandline-parameter "--data-dir"

- lang/qet_de.ts
- sources/editor/graphicspart/partdynamictextfield.cpp
- sources/editor/graphicspart/partpolygon.cpp
- sources/editor/graphicspart/partrectangle.cpp
- sources/editor/graphicspart/partrectangle.h
- remove dead code (local variables that were never used)
- typos
- white space
- comments
> minor changes

- sources/qetgraphicsitem/qetshapeitem.cpp
as discussed here:
[https://github.com/qelectrotech/qelectrotech-source-mirror/pull/338#issuecomment-2629343083](url)
> remove dead code (local variables that were never used)

- sources/exportdialog.cpp
- sources/exportdialog.h
see also discussion in QET-Forum from here:
https://qelectrotech.org/forum/viewtopic.php?pid=21000#p21000
> export: set maximum width / height according specifications of export-type

- sources/exportdialog.cpp
- sources/exportdialog.h
see: [https://qelectrotech.org/forum/viewtopic.php?pid=21015#p21015](url)
> export: set maximum width / height according limitations in QPainter

- sources/ElementsCollection/xmlelementcollection.cpp
- sources/diagramcontext.cpp
and sorted translations for "imported elements" in source-code
> fix: properties in project-file

- sources/editor/elementscene.cpp
- sources/editor/graphicspart/partarc.cpp
- sources/editor/graphicspart/partdynamictextfield.cpp
- sources/editor/graphicspart/partellipse.cpp
- sources/editor/graphicspart/partline.cpp
- sources/editor/graphicspart/partpolygon.cpp
- sources/editor/graphicspart/partrectangle.cpp
- sources/editor/graphicspart/parttext.cpp
- sources/properties/terminaldata.cpp
limit decimal places for floats
and typos and whitespace -corrections
> some cleaning for element-file

- sources/editor/ui/qetelementeditor.cpp
- sources/editor/ui/qetelementeditor.ui
- sources/qetdiagrameditor.cpp
- sources/qetgraphicsitem/ViewItem/qetgraphicstableitem.cpp
- sources/qetgraphicsitem/conductor.cpp
- sources/qetgraphicsitem/crossrefitem.cpp
- sources/qetgraphicsitem/qetgraphicsitem.cpp
- sources/qetgraphicsitem/terminal.cpp
- sources/richtext/richtexteditor.cpp
- sources/undocommand/movegraphicsitemcommand.cpp
> a few translated shortcuts were still there ... fixed!

- sources/editor/elementprimitivedecorator.cpp
- sources/editor/elementprimitivedecorator.h
- sources/editor/graphicspart/partarc.cpp
- sources/editor/graphicspart/partarc.h
- sources/editor/graphicspart/partellipse.cpp
- sources/editor/graphicspart/partellipse.h
- sources/editor/graphicspart/partline.cpp
- sources/editor/graphicspart/partline.h
- sources/editor/graphicspart/partpolygon.cpp
- sources/editor/graphicspart/partpolygon.h
- sources/editor/graphicspart/partrectangle.cpp
- sources/editor/graphicspart/partrectangle.h
- sources/qetgraphicsitem/ViewItem/qetgraphicstableitem.cpp
- sources/qetgraphicsitem/conductor.cpp
- sources/qetgraphicsitem/conductor.h
- sources/qetgraphicsitem/element.cpp
- sources/qetgraphicsitem/qetshapeitem.cpp
- sources/qetgraphicsitem/qetshapeitem.h
typos, whitespace and brackets
> minor: mostly typos

- sources/editor/graphicspart/partterminal.cpp
did not mirror/flip, when orientation was not changed --> fixed
> BugFix: Flip and Mirror of terminals

- sources/editor/editorcommands.cpp
- sources/editor/editorcommands.h
- sources/editor/graphicspart/partdynamictextfield.cpp
- sources/editor/graphicspart/partdynamictextfield.h
- sources/editor/graphicspart/partellipse.cpp
- sources/editor/graphicspart/partline.cpp
- sources/editor/graphicspart/partpolygon.cpp
- sources/editor/graphicspart/parttext.cpp
- sources/editor/graphicspart/parttext.h
- sources/editor/ui/qetelementeditor.cpp
- sources/editor/ui/qetelementeditor.ui
- sources/factory/elementpicturefactory.cpp
- sources/qet.cpp
The “text” elements look so harmless, but are tricky to mirror and flip!
I'll have to sleep on it for another night or two...
> some more rotation, mirror and flip

- sources/TerminalStrip/terminalstrip.cpp
- sources/dataBase/projectdatabase.cpp
- sources/dataBase/ui/elementquerywidget.cpp
- sources/diagramevent/diagrameventaddelement.cpp
- sources/editor/editorcommands.cpp
- sources/editor/elementscene.cpp
- sources/editor/graphicspart/partdynamictextfield.cpp
- sources/editor/graphicspart/parttext.cpp
- sources/editor/graphicspart/parttext.h
- sources/editor/ui/elementpropertieseditorwidget.cpp
- sources/elementprovider.cpp
- sources/properties/elementdata.cpp
- sources/properties/elementdata.h
- sources/qetdiagrameditor.cpp
- sources/qetgraphicsitem/element.cpp
- sources/ui/elementinfowidget.cpp
for further information read texts in commits
> element-editor: add mirror and flip for "text"

- sources/editor/ui/qetelementeditor.cpp
and removed qDebug() - Output.
Seems to work for me but should be tested by someone else, too.
> added code for Qt6 to qetelementeditor.cpp

- sources/editor/graphicspart/partarc.cpp
- sources/editor/graphicspart/partellipse.cpp
- sources/editor/graphicspart/partline.cpp
- sources/editor/graphicspart/partpolygon.cpp
- sources/editor/graphicspart/partrectangle.cpp
- sources/editor/graphicspart/partterminal.cpp
... as Achim also reported in [QET-Forum](https://qelectrotech.org/forum/viewtopic.php?pid=21199#p21199)
> element-editor: fix jumping positions when rotate, mirror or flip

- sources/qetgraphicsitem/conductor.cpp
- sources/qetgraphicsitem/element.cpp
> adjust zoom-factor to use cosmetic-line and fixed comments

- sources/bordertitleblock.cpp
- sources/conductornumexport.cpp
- sources/conductorproperties.cpp
- sources/diagram.cpp
- sources/diagramview.cpp
- sources/elementspanelwidget.cpp
- sources/elementtextpattern.cpp
- sources/exportdialog.cpp
- sources/exportproperties.cpp
- sources/machine_info.cpp
- sources/machine_info.h
- sources/print/projectprintwindow.cpp
- sources/titleblock/templatelogomanager.cpp
- and titleblock - templatelogomanager
- removed some Qt-version-checks
- string-concatenation with "%" instead of "+"
- add some changes already made in master-branch and elevatormind's qt6-cmake
> FIX broken signals in export-dialog

- sources/diagram.cpp
- sources/diagramview.cpp
- sources/editor/elementview.cpp
- sources/qet.cpp
- sources/qetdiagrameditor.cpp
- sources/qetgraphicsitem/conductor.cpp
- sources/qetgraphicsitem/terminal.cpp
> only calculate grid-point-size, when min != max

- sources/diagram.cpp
After the commit 'Correcting dynamicElementTextItem alignment on copying', not all composite text was displayed correctly. As soon as the composite text contained multiple variables in a line or user text, the alignment was no longer correct. Furthermore, the text value was not correctly written to the clipboard, so it was no longer present when pasting. I have corrected these errors here.
> Correct compositeText alignment on copying

- sources/ElementsCollection/elementscollectionmodel.cpp
- sources/ElementsCollection/elementscollectionwidget.cpp
- sources/ElementsCollection/elementstreeview.cpp
- sources/print/projectprintwindow.cpp
- sources/qetdiagrameditor.cpp
- sources/qetmainwindow.cpp
- sources/titleblock/qettemplateeditor.cpp
- sources/ui/titleblockpropertieswidget.cpp
I work with QET every day and have noticed some errors that lead to crashes. For myself, I worked under Linux with Wayland, but I think some of these errors are also affected by other distros.
> Minor corrections to prevent crashes
