sources/exportpropertieswidget.cpp

it is not necessary here and only confuses the user ...

hide SVG background checkbox in print preferences

---

sources/editor/ui/terminaleditor.cpp

Element-Editor:
SpinBoxes for x- and y-Position of terminals lose focus after every keystroke.
Try to fix that.

fix: editing SpinBoxes with keyboard lose focus

---

sources/qetgraphicsitem/conductor.cpp
sources/qetgraphicsitem/terminal.cpp
sources/qetgraphicsitem/terminal.h

It may be a good idea to add the terminal-names to the connections in QET-file. 
This could make it easier for a programmer of an external tool or plugin to develop something...

add terminal-names to connection in qet-file

---

sources/qetgraphicsitem/conductor.cpp

In my opinion, we should move the code Laurent inserted for the tags "element1_linked" and "element2_linked" to the else branch of the IF query for the UUID of the terminal to avoid possible crashes? Users may still have elements in their projects and/or collections that do not have a UUID.

move code into else-clause to avoid possible crashes

---

sources/qet_elementscaler/qet_elementscaler.cpp

There is no special need for this PR as the message-box will "only" be shown, if single parts of the imported elmt-file had to be dropped...

use MessageBox to inform user about additional info when importing scaled element

---

sources/ElementsCollection/elementstreeview.cpp

When in dark mode, symbols shown in collections menu are very difficult to view.
Forcing bright palette (like projects tree already does) solves the issue for me.
This is probably not the best way to code it (duplicated code), this palette should ideally be created in one place and reused. Feel free to adapt my suggestions in any way you like.

Force light mode in collections like projects

---

sources/qetproject.cpp
sources/ui/configpage/configpages.cpp

Fixed bug found by LievenC: 
[https://qelectrotech.org/forum/viewtopic.php?id=2856](url)

Fix missing company-titleblocks in properties-dialog

---

sources/conductornumexport.cpp
sources/dataBase/projectdatabase.cpp
sources/diagramevent/diagrameventaddimage.cpp
sources/exportproperties.cpp
sources/qetapp.cpp
sources/qetapp.h
sources/qetdiagrameditor.cpp
sources/qetproject.cpp
sources/titleblock/templatelogomanager.cpp
sources/ui/bomexportdialog.cpp

All export files that are derived from the project (BOM, nomenclature, etc.) are saved in the same directory by default. 
In this context, the standard directories have been grouped together in qetapp.cpp / qetapp.h so that only one place needs to be searched for in case of any adjustments.

Set default-location for projects to documents-dir.

---

sources/machine_info.cpp

The custom elements were counted twice instead of adding company-elements...

machine_info: fix element-count and make static text a bit shorter

---

build-aux/snap/snapcraft.yaml

Fix traceback when selecting "Project" menu "Launch the terminal block creation plugin" item:
Traceback (most recent call last):
File "/snap/qelectrotech/1973/bin/qet_tb_generator", line 33, in <module>
sys.exit(load_entry_point('qet-tb-generator==1.3.1', 'console_scripts', 'qet_tb_generator')())
File "/snap/qelectrotech/1973/bin/qet_tb_generator", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
module = import_module(match.group('module'))
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in …

build-aux/snap/snapcraft.yaml:  python3.8 -> 3.10

---

sources/editor/ui/qetelementeditor.cpp
sources/editor/ui/qetelementeditor.h
sources/ui/configpage/generalconfigurationpage.cpp

Additionally:
Source-code compiles and binary runs perfectly without the removed function to call ElementScaler!

corrected a few places where QETApp::documentDir() should also be used

---

sources/qetdiagrameditor.cpp

Now it's better readable and maintainable up to the moment we have our own internal Terminal-Manager for productive use. Additionally added the storage location “dataDir()/binary”, so that the new structure for the separation of
configuration and data can be properly kept.
We can remove the inserted qInfo() - lines later, when we know that everything is o.k. with this part of code. On my Debian stable and unstable the code works perfectly!

rewrite code for executing “qet_tb_generator” plugin

---

sources/machine_info.cpp

We use QETApp::configDir() to save configuration-files (*.json) for creating BOM, nomenclature, etc. during runtime. So it's interesting for win-users, too, which configDir is used.

machine_info: add entry for QETApp::configDir() also for win

---

sources/qetdiagrameditor.cpp

to avoid misunderstandings:
as long as plugin is searched, "not found: search-location" is logged
as soon as the plugin is found, the search ends and the place of plugin is written to log

more precise Log-Text for search of "qet_tb_generator"

---

sources/editor/elementscene.cpp
sources/editor/elementview.cpp
sources/qetgraphicsitem/ViewItem/qetgraphicstableitem.cpp

"_Why keep it simple when you can make it complicated?_"
Really???
I prefer:
**Keep it small and simple!**
The paste position is equal to the copied position plus an integer offset in x-direction right of the copied selection or the last pasted parts.
If the copied selection contains decimal places for the position, they are of course also retained in the copy! We don't want falsified copies ...!
Note:
This fix does not mean that we should revert the limitation of decimal places: These are two separate issues!

FIX copy-and-paste in element-editor: set paste-position to meaningful values

---

sources/editor/elementscene.cpp
sources/editor/elementscene.h

When saving an element it is checked, if the origin (0/0) is inside the graphical parts. If outside, the element is moved by integer values for x- and y-offset before saving. Old calculation for offset could lead to "strange" new values for positions.
Additionally: fix typos and English comments

fix movement of element, when origin is outside of graphics

---

sources/qetgraphicsitem/dynamicelementtextitem.cpp
sources/ui/elementpropertieswidget.cpp

While searching for something different i saw that there is a settings key not written in a consistent way. So in some places it was already spelled `dynamic_text_width` but within evaluation it was written `dynamic_text_widht` which is only a typo i think.
I fixed this and found another place where it was spelled wrong as well
I did not do testing on this cause i do not really know what is meant here.

Fix typo widht to width

---

sources/qetgraphicsitem/dynamicelementtextitem.cpp

as mentioned in [QET-Forum](https://qelectrotech.org/forum/viewtopic.php?pid=21117#p21117): 
the additional ControlModifier does not work as intended but moves the view in diagram-editor

some small changes for selective move

---

sources/bordertitleblock.cpp

... by using datatype "char" for single letter. 
This is possible, because we use only latin-letters "A .. Z, AA .. AZ, ..." for numbering rows in diagram-editor, no matter what language the user has set in program-settings.

bordertitleblock: use same code for Qt5 & Qt6 for "numbering" rows

---

sources/editor/graphicspart/partarc.cpp
sources/editor/graphicspart/partellipse.cpp
sources/editor/graphicspart/partline.cpp
sources/editor/graphicspart/partrectangle.cpp
sources/editor/graphicspart/partterminal.cpp
sources/qetgraphicsitem/terminal.cpp

When reading and comparing [Qt5-docs](https://qthub.com/static/doc/qt5/qtwidgets/qstyleoptiongraphicsitem.html#levelOfDetailFromTransform) and [Qt6-docs](https://doc.qt.io/qt-6/qstyleoptiongraphicsitem.html#levelOfDetailFromTransform), I read, that there are no differences in the functions!
So it is not necessary to have the differentiation between the Qt-Versions.
Code compiles without errors or warnings for Qt5 and Qt6 and there are no visible differences in elements.
But check yourself, before merging...

simplify and use the same code for Qt5 & Qt6

---

sources/ElementsCollection/xmlelementcollection.cpp
sources/editor/UndoCommand/openelmtcommand.cpp
sources/editor/graphicspart/partpolygon.cpp
sources/qetapp.cpp
sources/qetgraphicsitem/ViewItem/qetgraphicstableitem.cpp
sources/qetgraphicsitem/element.cpp
sources/qetproject.cpp
sources/qetproject.h
sources/undocommand/deleteqgraphicsitemcommand.cpp
sources/undocommand/deleteqgraphicsitemcommand.h

- set default-value for QFont::Weight to prevent warning at runtime
- remove unused NamesList from qetproject.cpp / qetproject.h
- unify NamesList "imported elements" to be used with Qt5 & Qt6
we still need to decide whether to use list of QChars or written text in utf-8; kept both variants for now
- corrected comment
- use same code for Qt5 & Qt6 for XRef-list
Until now the code was just added for Qt6, but it can be used by Qt5 as well.

unify some more code for Qt5 & Qt6 (and more)

---

sources/qetgraphicsitem/diagramtextitem.cpp

- Added text for dynamic text item to indicate that shift needs to be held down to move the text.

Mouse hover text for dynamic text items

---

sources/autoNum/assignvariables.cpp
sources/diagram.cpp
sources/diagram.h
sources/diagramview.cpp
sources/qetgraphicsitem/dynamicelementtextitem.cpp

with translator:
commit: correcting the visibility of Variables in CompositeText
When a report element with composite text from the collection is inserted into the diagram, the variable name is displayed, e.g. %{function} . The element works perfectly, but of course, it doesn't look good. This is corrected here. 
commit: Correcting dynamicElementTextItem alignment on copying
We have the problem that after copying elements with right-aligned text (and centered text), the text gets an offset to the left by the text width. The cause is the text insertion point, which is not constant for right-aligned text, but changes according to the text width. When copying, the insertion point of the labeled text is copied to the clipboard and then used as the insertion point for empty text when pasting …

A few small improvements
